version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8088:8088"
    links:
      - mongo_db:app_db
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_db:27017/gitty
    env_file:
      - .env
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - "27017:27017"