version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8088:8088"
    links:
      - mongo_db:app_db
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_db:27017/gitty
    env_file:
      - .env
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    volumes:
      - /data/db:/data/db
  nginx:
    container_name: my-nginx
    image: nginx
    ports:
      - "81:81"
      - "443:443"
    depends_on:
      - "api_service"
    volumes:
      - /etc/letsencrypt/live/gitty.shop/fullchain.pem:/etc/letsencrypt/live/gitty.shop/fullchain.pem
      - /etc/letsencrypt/live/gitty.shop/privkey.pem:/etc/letsencrypt/live/gitty.shop/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      - /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf