server:
  port: 8088

spring:
  application:
    name: gitty
  webflux:
    base-path: /gitty
  data.mongodb.uri: mongodb://localhost:27017/gitty

gitlab:
  baseUrl: *
  token: *

telegram:
  bot.name: tg_gitty_bot
  bot.token: *