server:
  port: 8088

spring:
  application:
    name: gitty
  webflux:
    base-path: /gitty
  data.mongodb.uri: mongodb://localhost:27017/gitty

gitlab:
  baseUrl: ${GITLAB_BASE_URL}
  token: ${GITLAB_TOKEN}

telegram:
  bot.name: ${BOT_NAME}
  bot.token: ${BOT_TOKEN}