spring:
  application:
    name: gitty
  data.mongodb.uri: mongodb://localhost:27017/gitty
server:
  port: 8088


gitlab:
  baseUrl: http://cm-dev.fisgroup.ru:8888/

telegram:
  bot.name: tg_gitty_bot
  bot.token: XXX
