spring:
  application:
    name: gitty
  webflux:
    base-path: /gitty
  data.mongodb.uri: mongodb://localhost:27017/gitty
server:
  port: 8088


gitlab:
  baseUrl: *

telegram:
  bot.name: tg_gitty_bot
  bot.token: *
